version: "3"
services:
  school:
    image: appointmentguru/infrastructure:latest
    volumes:
      - ./production.environment.yml:/code/ansible/group_vars/server_swarm.yml
      - ~/.ssh:/root/.ssh # map ssh keys
    command: ansible-playbook /code/ansible/deploy.drf.yml  -i /etc/ansible/inventory/digital_ocean.py -e "organization=appointmentguru service=codeguru entity_name=code" --skip-tags=kong
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_LIBRARY=/etc/ansible/library
