# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170611_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='icd10code',
            name='see',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
