# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_icd10code_see'),
    ]

    operations = [
        migrations.AddField(
            model_name='icd10code',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
