# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 10:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_icd10code_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('includes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text="The word 'Includes' appears immediately under certain categories to further define, or give examples of, the content of the category.", null=True, size=None)),
                ('excludes1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text="A type 1 Excludes note is a pure excludes.  It means 'NOT CODED HERE!'  An Excludes1 note indicates that the code excluded should never be used at the same time as the code above the Excludes1 note.  An Excludes1 is used when two conditions cannot occur together, such as a congenital form versus an acquired form of the same condition.", null=True, size=None)),
                ('excludes2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text="A type 2 excludes note represents 'Not included here'.  An excludes2 note indicates that the condition excluded is not part of the condition it is excluded from but a patient may have both conditions at the same time.  When an Excludes2 note appears under a code it is acceptable to use both the code and the excluded code together.", null=True, size=None)),
                ('code_first', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text="Certain conditions have both an underlying etiology and multiple body system manifestations due to the underlying etiology.  For such conditions the ICD-10-CM has a coding convention that requires the underlying condition be sequenced first followed by the manifestation.  Wherever such a combination exists there is a 'use additional code' note at the etiology code, and a 'code first' note at the manifestation code.  These instructional notes indicate the proper sequencing order of the codes, etiology followed by manifestation. In most cases the manifestation codes will have in the code title, 'in diseases classified elsewhere.'  Codes with this title are a component of the etiology/ manifestation convention. The code title indicates that it is a manifestation code.  'In diseases classified elsewhere' codes are never permitted to be used as first listed or principal diagnosis codes. They must be used in conjunction with an underlying condition code and they must be listed following the underlying condition.", null=True, size=None)),
                ('code_also', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='A code also note instructs that 2 codes may be required to fully describe a condition but the sequencing of the two codes is discretionary, depending on the severity of the conditions and the reason for the encounter.', null=True, size=None)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Code')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Section'),
        ),
    ]
