# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170717_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='code_first',
            new_name='inclusion_term',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='code_also',
            new_name='use_additional_code',
        ),
    ]
