# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170718_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('practice_type_code', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('discovery_rate', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='code',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
